In [1]:
import numpy as np
x=np.array([[1,2,3]])
x

array([[1, 2, 3]])

In [2]:
x.dtype

dtype('int32')

In [3]:
type(x)

numpy.ndarray

In [4]:
x.ndim

2

In [5]:
x.size

3

In [6]:
x.shape

(1, 3)

In [7]:
import numpy as np
x=np.array([[1,2,3],[5,6,7]])
x

array([[1, 2, 3],
       [5, 6, 7]])

In [9]:
x=np.ones((3,3),dtype=float)
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [11]:
x.dtype

dtype('float64')

In [12]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [13]:
x=np.arange(1,13).reshape(3,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
x.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [15]:
x.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
import numpy as np
x1=np.arange(1,10).reshape(3,3)
x2=np.arange(1,10).reshape(3,3)
x1+x2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [17]:
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
x2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
x1*x2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [20]:
x1-x2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
np.multiply(x1,x2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [22]:
np.add(x1,x2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [23]:
np.subtract(x1,x2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
x1@x2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [25]:
x1.dot(x2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [26]:
x1.max()

9

In [27]:
x2.max()

9

In [28]:
x2.argmax()

8

In [29]:
x1.max(axis=1)

array([3, 6, 9])

In [30]:
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
x1.max(axis=0)

array([7, 8, 9])

In [32]:
x1.min()

1

In [33]:
x1.min(axis=1)

array([1, 4, 7])

In [34]:
x1.sum()

45

In [35]:
x1.sum(axis=1)

array([ 6, 15, 24])

In [36]:
x1.mean()

5.0

In [37]:
np.mean(x1)

5.0

In [38]:
np.sqrt(x1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [39]:
np.std(x1)

2.581988897471611

In [40]:
np.log(x1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [41]:
np.log10(x1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [42]:
np.exp(x1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [44]:
import numpy as np
x=np.arange(1,101).reshape(10,10)
x


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [45]:
x[1,4]

15

In [46]:
x[2:3,2:3]

array([[23]])

In [47]:
np.concatenate((x1,x2))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
np.hstack((x1,x2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [49]:
np.vstack((x1,x2))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
x3=np.arange(1,10).reshape(3,3)
x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.vstack((x1,x2,x3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
np.split(x1,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [56]:
x=np.array([2,3,5,7,9])
x

array([2, 3, 5, 7, 9])

In [58]:
np.split(x,[1,4])

[array([2]), array([3, 5, 7]), array([9])]

In [59]:
np.sin(180)

-0.8011526357338304